-- =============================================================================
-- F-52 — Aviso de imprevisto: the one-tap notice about TODAY
--
-- The most frequent real event in shared custody is the one the product did
-- not serve at all: the day does not change, so the swap workflow is the wrong
-- tool, and the day observation is a PLAN note, not something that interrupts
-- anyone — so the parent opens WhatsApp, which is precisely the coordination
-- this app exists to take off WhatsApp.
--
-- **Aviso is the third term**, beside *Observação do dia* (a note attached to a
-- date) and *Mensagem* (the F-44 text two parties exchange while negotiating a
-- swap): one-way, about right now, tied to today. U-34 reserved the word
-- before a string was written; this item spends it.
--
-- **The invariant the card carried, and what replaced it** (owner,
-- 18/09/2026). The card said an aviso NEVER changes `actual_parent`. That
-- still holds for the aviso itself. What changed is that an aviso may ASK for
-- the day (`request = 'keep'`), and — in this item's second PR — the ANSWER to
-- such an aviso opens a swap that is already approved: by then both parties
-- have consented in order and on the record, the sender by asking and the
-- answerer by accepting. `actual_parent` therefore still moves only through
-- the two-party workflow, with its freezing, its audit stamps and its F-45
-- origin link. No second path is opened, which is what §2 of the standing
-- decisions forbids.
--
-- **A stated delay closes that door.** If the sender says "30 minutes", the
-- most anyone can offer is to hold the child until they arrive; only an
-- open-ended imprevisto can put the day itself on offer. Hence the CHECK
-- pairing `request = 'keep'` with `eta_minutes IS NULL`, and the second half
-- of that rule — the sender must be the carer whose day it is — in
-- `send_day_notice`, because only a lookup can answer it.
--
-- **Who may send.** The product does NOT model "who is holding the child right
-- now": a day has ONE effective responsible for its whole length, and
-- `handoff_time` is the hour of the transition, not a second owner. So the two
-- ends of a handover are named through the days around this one — today's
-- carer, yesterday's (whose handover is happening) and the next different
-- day's (whose collection is coming). Mirrored in `noticeSenderIds`.
--
-- **Append-only by GRANT, not by trigger** — the `account_logs` shape (S-10).
-- `authenticated` gets SELECT and nothing else; every write is inside a
-- SECURITY DEFINER function owned by postgres. A trigger refusing DELETE would
-- also refuse the cascade that a family purge depends on.
--
-- **One outcome per notice, enforced by a UNIQUE.** Two carers tapping "eu
-- fico" in the same second is not a rare case, it is the case — the second one
-- is refused by the database rather than by a check the client could lose a
-- race on. Cancelling is an outcome too, authored by the sender: the row stays,
-- because a record that can be edited is not a record.
--
-- What ships here (PR 1 of 3): the tables, the guards, sending, cancelling and
-- the notification. The two answers and the approved swap are PR 2; push is
-- PR 3.
-- =============================================================================

-- ── 1. day_notices ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.day_notices (
	id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	family_id         bigint NOT NULL REFERENCES public.families (id) ON DELETE CASCADE,
	schedule_date     date   NOT NULL,
	sender_profile_id bigint NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
	reason            text   NOT NULL CHECK (reason IN ('atraso', 'medico', 'transito', 'outro')),
	eta_minutes       int    CHECK (eta_minutes IN (15, 30, 60)),
	request           text   NOT NULL CHECK (request IN ('info', 'pickup', 'keep')),
	note              text   CHECK (note IS NULL OR char_length(note) <= 140),
	created_at        timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL,

	-- Half of the rule, the half a CHECK can state. The other half (the sender
	-- must be the day's carer) needs a lookup and lives in send_day_notice.
	CONSTRAINT day_notices_keep_needs_open_end
		CHECK (request <> 'keep' OR eta_minutes IS NULL)
);

CREATE INDEX IF NOT EXISTS day_notices_family_date_idx
	ON public.day_notices (family_id, schedule_date DESC, created_at DESC);

-- The cap reads this one: two per sender per day.
CREATE INDEX IF NOT EXISTS day_notices_sender_date_idx
	ON public.day_notices (sender_profile_id, schedule_date);

COMMENT ON TABLE public.day_notices IS
	'F-52: a one-way notice about TODAY that does not change who has the child. Append-only — authenticated holds SELECT only; writes go through send_day_notice.';
COMMENT ON COLUMN public.day_notices.eta_minutes IS
	'F-52: the stated estimate, or NULL for "sem previsão". NULL is a VALUE here, not a gap: it is the only state in which the day itself may be offered (request = keep).';
COMMENT ON COLUMN public.day_notices.request IS
	'F-52: what the sender needs. info = nothing; pickup = help now, the day unchanged; keep = the day is on offer, and its answer opens an already-approved swap (PR 2).';

ALTER TABLE public.day_notices OWNER TO postgres;
ALTER TABLE public.day_notices ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.day_notices FROM PUBLIC;
REVOKE ALL ON TABLE public.day_notices FROM anon;
REVOKE ALL ON TABLE public.day_notices FROM authenticated;
GRANT SELECT ON TABLE public.day_notices TO authenticated;
GRANT ALL    ON TABLE public.day_notices TO service_role;

DROP POLICY IF EXISTS day_notices_family_read ON public.day_notices;
CREATE POLICY day_notices_family_read ON public.day_notices
	FOR SELECT TO authenticated
	USING (family_id = public.get_my_family_id());

-- ── 2. day_notice_outcomes ───────────────────────────────────────────────────
-- One row closes a notice, for good. The UNIQUE on notice_id IS the race
-- guard: whoever commits first resolves it, and the loser gets a unique
-- violation instead of a second answer nobody expected.
--
-- `outcome` accepts only 'cancelled' here. 'helping' and 'keeping' arrive with
-- PR 2, together with the code that makes them mean something — a value the
-- schema accepts and no function can produce is a promise the product does not
-- keep, and a merge to `main` reaches real users.

CREATE TABLE IF NOT EXISTS public.day_notice_outcomes (
	id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	notice_id        bigint NOT NULL UNIQUE REFERENCES public.day_notices (id) ON DELETE CASCADE,
	outcome          text   NOT NULL CHECK (outcome IN ('cancelled')),
	actor_profile_id bigint NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
	note             text   CHECK (note IS NULL OR char_length(note) <= 140),
	swap_request_id  bigint REFERENCES public.swap_requests (id) ON DELETE SET NULL,
	created_at       timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL
);

COMMENT ON TABLE public.day_notice_outcomes IS
	'F-52: the single row that closes a day_notice. UNIQUE (notice_id) is the concurrency guard. Append-only, like the notice itself.';

ALTER TABLE public.day_notice_outcomes OWNER TO postgres;
ALTER TABLE public.day_notice_outcomes ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.day_notice_outcomes FROM PUBLIC;
REVOKE ALL ON TABLE public.day_notice_outcomes FROM anon;
REVOKE ALL ON TABLE public.day_notice_outcomes FROM authenticated;
GRANT SELECT ON TABLE public.day_notice_outcomes TO authenticated;
GRANT ALL    ON TABLE public.day_notice_outcomes TO service_role;

DROP POLICY IF EXISTS day_notice_outcomes_family_read ON public.day_notice_outcomes;
CREATE POLICY day_notice_outcomes_family_read ON public.day_notice_outcomes
	FOR SELECT TO authenticated
	USING (EXISTS (
		SELECT 1 FROM public.day_notices n
		WHERE n.id = notice_id
		  AND n.family_id = public.get_my_family_id()));

-- ── 3. The sentence, in one place ────────────────────────────────────────────
-- The stored `title`/`message` are the PT-BR FALLBACK (U-13): every reader
-- rebuilds the sentence from `params` in their OWN language, and this text is
-- what survives a payload we cannot parse. It must stay byte-identical to the
-- PT-BR catalog — `day_notice.dart` in the DB gate asserts exactly that, for
-- every combination, against a real database.

CREATE OR REPLACE FUNCTION public.day_notice_sentence(
	p_sender_name text,
	p_reason      text,
	p_eta_minutes int,
	p_request     text,
	p_note        text)
RETURNS text
LANGUAGE sql IMMUTABLE
AS $$
	SELECT p_sender_name || ' avisou que '
		|| CASE p_reason
			WHEN 'atraso'   THEN 'vai atrasar'
			WHEN 'medico'   THEN 'teve um imprevisto médico'
			WHEN 'transito' THEN 'está preso no trânsito'
			ELSE                 'teve um imprevisto'
		   END
		|| CASE WHEN p_eta_minutes IS NULL
			THEN ' (sem previsão)'
			ELSE ' (cerca de ' || p_eta_minutes || ' min)'
		   END
		|| CASE p_request
			WHEN 'pickup' THEN ' e precisa que alguém busque a criança.'
			WHEN 'keep'   THEN ' e precisa que alguém fique com a criança hoje.'
			ELSE               '.'
		   END
		|| CASE WHEN p_note IS NULL THEN '' ELSE ' "' || p_note || '"' END;
$$;

ALTER FUNCTION public.day_notice_sentence(text, text, int, text, text) OWNER TO postgres;

-- ── 4. send_day_notice ───────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.send_day_notice(
	p_reason      text,
	p_eta_minutes int  DEFAULT NULL,
	p_request     text DEFAULT 'info',
	p_note        text DEFAULT NULL)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	me            public.profiles%ROWTYPE;
	today         date := (now() AT TIME ZONE 'America/Sao_Paulo')::date;
	day_parent    bigint;
	prev_parent   bigint;
	next_parent   bigint;
	note          text := nullif(btrim(p_note), '');
	sent_today    int;
	new_id        bigint;
	sentence      text;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();

	-- A frozen member (S-11) holds no seat and acts on nothing; a pending one
	-- (F-56) has no account to act with, so it can never reach this anyway.
	IF me.id IS NULL OR me.left_at IS NOT NULL THEN
		RAISE EXCEPTION 'Sua conta não pode enviar avisos.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	IF note IS NOT NULL AND char_length(note) > 140 THEN
		RAISE EXCEPTION 'O detalhe do aviso é limitado a 140 caracteres.'
			USING ERRCODE = 'check_violation';
	END IF;

	-- The three ends of the day, mirrored from `noticeSenderIds`.
	SELECT COALESCE(cs.actual_parent_id, cs.scheduled_parent_id) INTO day_parent
	FROM public.care_schedules cs
	WHERE cs.family_id = me.family_id AND cs.schedule_date = today;

	SELECT COALESCE(cs.actual_parent_id, cs.scheduled_parent_id) INTO prev_parent
	FROM public.care_schedules cs
	WHERE cs.family_id = me.family_id AND cs.schedule_date = today - 1;

	-- The next day whose effective carer DIFFERS — the same forward scan the
	-- Hoje card's next-handoff line does, inside the same 90-day window
	-- (`nextHandoffWindowDays`). Unplanned days are simply not rows, so a gap
	-- is skipped rather than read as a change of carer.
	SELECT COALESCE(cs.actual_parent_id, cs.scheduled_parent_id) INTO next_parent
	FROM public.care_schedules cs
	WHERE cs.family_id = me.family_id
	  AND cs.schedule_date > today
	  AND cs.schedule_date <= today + 90
	  AND COALESCE(cs.actual_parent_id, cs.scheduled_parent_id) IS DISTINCT FROM day_parent
	ORDER BY cs.schedule_date
	LIMIT 1;

	IF me.id IS DISTINCT FROM day_parent
	   AND me.id IS DISTINCT FROM prev_parent
	   AND me.id IS DISTINCT FROM next_parent THEN
		RAISE EXCEPTION 'Um aviso é de quem está no meio da troca do dia: quem está com a criança hoje, quem entregou hoje, ou quem recebe na próxima troca.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	-- Only the carer whose day it is may put that day on offer. This is also
	-- what keeps PR 2's swap inside F-28: the answerer proposes THEMSELVES on
	-- the sender's own day (scenario A), never a third party on someone else's.
	IF p_request = 'keep' AND me.id IS DISTINCT FROM day_parent THEN
		RAISE EXCEPTION 'Só quem está com o dia de hoje pode oferecê-lo.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	-- Two a day (F-52): one covers the event, the second covers it getting
	-- worse. A third is a conversation, and that is F-35. A cancelled notice
	-- still counts — send-and-cancel would otherwise be an unbounded channel.
	SELECT count(*)::int INTO sent_today
	FROM public.day_notices
	WHERE sender_profile_id = me.id AND schedule_date = today;

	IF sent_today >= 2 THEN
		RAISE EXCEPTION 'Você já enviou 2 avisos hoje. O limite volta amanhã.'
			USING ERRCODE = 'check_violation';
	END IF;

	INSERT INTO public.day_notices
		(family_id, schedule_date, sender_profile_id, reason, eta_minutes, request, note)
	VALUES (me.family_id, today, me.id, p_reason, p_eta_minutes, p_request, note)
	RETURNING id INTO new_id;

	sentence := public.day_notice_sentence(
		me.full_name, p_reason, p_eta_minutes, p_request, note);

	-- Everyone with an account except the sender. F-09's rule holds: push only
	-- what the recipient did NOT just do, so the sender never gets a receipt.
	INSERT INTO public.notifications (recipient_profile_id, type, title, message, params)
	SELECT p.id, 'day_notice', 'Aviso de imprevisto', sentence,
	       jsonb_strip_nulls(jsonb_build_object(
	           'kind',   p_request,
	           'reason', p_reason,
	           'eta',    p_eta_minutes::text,
	           'note',   note,
	           'name',   me.full_name,
	           'date',   to_char(today, 'YYYY-MM-DD')))
	FROM public.profiles p
	WHERE p.family_id = me.family_id
	  AND p.id <> me.id
	  AND p.left_at IS NULL
	  AND p.user_id IS NOT NULL;

	RETURN new_id;
END;
$$;

ALTER FUNCTION public.send_day_notice(text, int, text, text) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.send_day_notice(text, int, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.send_day_notice(text, int, text, text) TO authenticated;
GRANT ALL    ON FUNCTION public.send_day_notice(text, int, text, text) TO service_role;

-- ── 5. cancel_day_notice ─────────────────────────────────────────────────────
-- The sender sorted it out, or it stopped being true. Whoever received it is
-- told, because somebody may be on their way.

CREATE OR REPLACE FUNCTION public.cancel_day_notice(p_notice_id bigint)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	me     public.profiles%ROWTYPE;
	notice public.day_notices%ROWTYPE;
	today  date := (now() AT TIME ZONE 'America/Sao_Paulo')::date;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();
	IF me.id IS NULL OR me.left_at IS NOT NULL THEN
		RAISE EXCEPTION 'Sua conta não pode cancelar avisos.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	SELECT * INTO notice FROM public.day_notices WHERE id = p_notice_id;

	-- One message for "not yours" and "does not exist": a caller learning
	-- which of the two it was learns about another family's rows.
	IF notice.id IS NULL
	   OR notice.family_id IS DISTINCT FROM me.family_id
	   OR notice.sender_profile_id IS DISTINCT FROM me.id THEN
		RAISE EXCEPTION 'Aviso não encontrado.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	-- A notice about a day that has passed cannot be withdrawn — there is
	-- nobody left to stop, and the record is the record.
	IF notice.schedule_date <> today THEN
		RAISE EXCEPTION 'Só o aviso de hoje pode ser cancelado.'
			USING ERRCODE = 'check_violation';
	END IF;

	-- The UNIQUE below would refuse it anyway; this says WHY.
	IF EXISTS (SELECT 1 FROM public.day_notice_outcomes o WHERE o.notice_id = notice.id) THEN
		RAISE EXCEPTION 'Este aviso já foi resolvido.'
			USING ERRCODE = 'check_violation';
	END IF;

	INSERT INTO public.day_notice_outcomes (notice_id, outcome, actor_profile_id)
	VALUES (notice.id, 'cancelled', me.id);

	INSERT INTO public.notifications (recipient_profile_id, type, title, message, params)
	SELECT p.id, 'day_notice', 'Aviso cancelado',
	       me.full_name || ' cancelou o aviso de hoje.',
	       jsonb_build_object(
	           'kind', 'cancelled',
	           'name', me.full_name,
	           'date', to_char(notice.schedule_date, 'YYYY-MM-DD'))
	FROM public.profiles p
	WHERE p.family_id = me.family_id
	  AND p.id <> me.id
	  AND p.left_at IS NULL
	  AND p.user_id IS NOT NULL;
END;
$$;

ALTER FUNCTION public.cancel_day_notice(bigint) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.cancel_day_notice(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.cancel_day_notice(bigint) TO authenticated;
GRANT ALL    ON FUNCTION public.cancel_day_notice(bigint) TO service_role;
