-- =============================================================================
-- F-75 — the other caregiver can answer a relato: a reply appended to it,
-- never an edit
--
-- Decisions locked by the owner (28/09/2026, competitive chain):
--   * The word is "Resposta" / "Reply". One reply per member per relato, plus
--     ONE correction by the same author (a new row; both kept). No reply to a
--     reply.
--   * Who answers: an active caregiver with an account who is NOT the relato's
--     author. A Visualizador only reads (`refuse_viewer_write` on the table).
--   * Append-only by GRANT, the F-67 shape: the client has SELECT and nothing
--     else; the only writer is `add_day_account_reply`. Nothing is written in
--     care_schedules or activity_logs, so no admin_override can ever stamp it.
--   * Keys: day_account_reply.window_days (30, 7–90, counted from when the
--     relato was WRITTEN), day_account_reply.max_chars (the relato's default),
--     feature.day_account_replies (born false; production flips it in a later
--     migration). Free, like the relato.
--   * The notice goes in-app to the relato's author only, a new type
--     `day_account_reply` that the push dispatcher's filter does not name (so
--     no push, and nothing there changes). A viewer never authors a relato,
--     so the F-50 notification filter never meets it.
--   * Every FK cascades exactly as day_accounts' do (family, author, relato,
--     corrected reply): the family purge and purge_e2e_family, both under
--     app.deletion_context, take the replies with the family without naming
--     the table — the gate proves it.
--   * F-69 counts them (a total and the corrections), never their text.
-- =============================================================================

-- ── 1. The keys (T-80 metadata, born explained) ─────────────────────────────

INSERT INTO public.app_settings
	(key, value, value_type, category, description, is_public, unit, impact, min_value, max_value, help)
VALUES
	('feature.day_account_replies', 'false', 'bool', 'features',
	 'Liga a resposta ao relato do dia (F-75).',
	 true, 'flag', 'critical', NULL, NULL,
	 jsonb_build_object(
		'controls', 'Se um responsável pode responder ao relato do dia que outro escreveu (add_day_account_reply).',
		'shown_at', jsonb_build_array('app'),
		'if_increased', 'Ligado: o botão Responder aparece sob o relato de outra pessoa, e o servidor aceita as respostas.',
		'if_decreased', 'Desligado: o servidor recusa respostas novas e o botão some; as respostas já gravadas continuam no registro.',
		'takes_effect', 'Servidor na próxima chamada; app na próxima abertura.',
		'caveats', 'Produção nasce desligada e é ligada por uma migração depois da conferência no QA.')),
	('day_account_reply.window_days', '30', 'int', 'product',
	 'Dias, desde que o relato foi escrito, para responder a ele (F-75).',
	 true, 'days', 'sensitive', 7, 90,
	 jsonb_build_object(
		'controls', 'Até quantos dias depois de o relato ser REGISTRADO a outra pessoa ainda pode responder a ele.',
		'shown_at', jsonb_build_array('app'),
		'if_increased', 'Respostas a relatos mais antigos passam a entrar no registro, no Histórico e no PDF.',
		'if_decreased', 'Relatos fora da nova janela deixam de aceitar resposta; as respostas já gravadas ficam.',
		'takes_effect', 'Servidor na próxima resposta; app na próxima abertura do dia.',
		'caveats', 'Conta da hora em que o relato foi escrito, não do dia a que ele se refere: um relato sobre D-30 escrito hoje ainda tem a janela inteira.')),
	('day_account_reply.max_chars', '1000', 'int', 'product',
	 'Tamanho máximo do texto de uma resposta a um relato (F-75).',
	 true, 'chars', 'normal', 100, 4000,
	 jsonb_build_object(
		'controls', 'Quantos caracteres cabem numa resposta ao relato do dia.',
		'shown_at', jsonb_build_array('app'),
		'if_increased', 'Respostas mais longas. Não passa de 4000: é o CHECK da coluna day_account_replies.body.',
		'if_decreased', 'Respostas mais curtas; as já gravadas ficam como estão.',
		'takes_effect', 'Servidor na próxima resposta; app na próxima abertura do dia.',
		'caveats', 'Nasce igual ao limite do relato (day_account.max_chars).'))
ON CONFLICT (key) DO NOTHING;

-- ── 2. The table: append-only by GRANT, read by the whole family ─────────────

CREATE TABLE IF NOT EXISTS public.day_account_replies (
	id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	family_id         bigint NOT NULL REFERENCES public.families (id) ON DELETE CASCADE,
	account_id        bigint NOT NULL REFERENCES public.day_accounts (id) ON DELETE CASCADE,
	author_profile_id bigint NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
	body              text   NOT NULL CHECK (char_length(body) BETWEEN 1 AND 4000),
	corrects_id       bigint REFERENCES public.day_account_replies (id) ON DELETE CASCADE,
	created_at        timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS day_account_replies_account_idx
	ON public.day_account_replies (account_id, created_at);
CREATE INDEX IF NOT EXISTS day_account_replies_family_idx
	ON public.day_account_replies (family_id, created_at);
-- One reply per member per relato (the original), and one correction of it.
CREATE UNIQUE INDEX IF NOT EXISTS day_account_replies_one_per_member_idx
	ON public.day_account_replies (account_id, author_profile_id) WHERE corrects_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS day_account_replies_one_correction_idx
	ON public.day_account_replies (corrects_id) WHERE corrects_id IS NOT NULL;

COMMENT ON TABLE public.day_account_replies IS
	'F-75: a reply to a relato do dia (day_accounts) by another caregiver. Append-only by GRANT; a correction is a new row pointing at the reply it corrects, both kept.';

ALTER TABLE public.day_account_replies OWNER TO postgres;
ALTER TABLE public.day_account_replies ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.day_account_replies FROM PUBLIC;
REVOKE ALL ON TABLE public.day_account_replies FROM anon;
REVOKE ALL ON TABLE public.day_account_replies FROM authenticated;
GRANT SELECT ON TABLE public.day_account_replies TO authenticated;
GRANT ALL    ON TABLE public.day_account_replies TO service_role;

DROP POLICY IF EXISTS day_account_replies_family_read ON public.day_account_replies;
CREATE POLICY day_account_replies_family_read ON public.day_account_replies
	FOR SELECT TO authenticated
	USING (family_id = public.get_my_family_id());

-- F-50: a new table of the plan gets the viewer guard in its own migration.
DROP TRIGGER IF EXISTS trigger_a_refuse_viewer_write ON public.day_account_replies;
CREATE TRIGGER trigger_a_refuse_viewer_write
	BEFORE INSERT OR UPDATE OR DELETE ON public.day_account_replies
	FOR EACH ROW EXECUTE FUNCTION public.refuse_viewer_write();

-- ── 3. The only writer ──────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.add_day_account_reply(
	p_account_id bigint,
	p_body text,
	p_corrects_id bigint DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	me          public.profiles%ROWTYPE;
	account     public.day_accounts%ROWTYPE;
	corrected   public.day_account_replies%ROWTYPE;
	window_days int := public.setting_int('day_account_reply.window_days', 30);
	max_chars   int := public.setting_int('day_account_reply.max_chars', 1000);
	body        text := nullif(btrim(p_body), '');
	new_id      bigint;
BEGIN
	IF NOT public.setting_bool('feature.day_account_replies', false) THEN
		RAISE EXCEPTION 'A resposta ao relato ainda não está disponível.'
			USING ERRCODE = 'feature_not_supported';
	END IF;

	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();
	IF me.id IS NULL OR me.left_at IS NOT NULL THEN
		RAISE EXCEPTION 'Sua conta não pode responder a relatos.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;
	IF me.membership_type IS DISTINCT FROM 'full' THEN
		RAISE EXCEPTION 'Visualizadores acompanham o plano da família sem alterar nada.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	SELECT * INTO account FROM public.day_accounts WHERE id = p_account_id;
	IF account.id IS NULL OR account.family_id IS DISTINCT FROM me.family_id THEN
		RAISE EXCEPTION 'Relato não encontrado.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;
	IF account.author_profile_id = me.id THEN
		RAISE EXCEPTION 'Quem escreveu o relato não responde a ele — para mudar o texto, registre uma correção.'
			USING ERRCODE = 'check_violation';
	END IF;
	IF now() > account.created_at + make_interval(days => window_days) THEN
		RAISE EXCEPTION 'Um relato pode receber resposta até % dias depois de registrado.', window_days
			USING ERRCODE = 'check_violation';
	END IF;

	IF body IS NULL THEN
		RAISE EXCEPTION 'A resposta não pode ficar vazia.'
			USING ERRCODE = 'check_violation';
	END IF;
	IF char_length(body) > max_chars THEN
		RAISE EXCEPTION 'A resposta é limitada a % caracteres.', max_chars
			USING ERRCODE = 'check_violation';
	END IF;

	IF p_corrects_id IS NULL THEN
		IF EXISTS (SELECT 1 FROM public.day_account_replies r
		           WHERE r.account_id = account.id AND r.author_profile_id = me.id
		             AND r.corrects_id IS NULL) THEN
			RAISE EXCEPTION 'Você já respondeu a este relato — para mudar o texto, registre uma correção.'
				USING ERRCODE = 'check_violation';
		END IF;
	ELSE
		SELECT * INTO corrected FROM public.day_account_replies WHERE id = p_corrects_id;
		-- One message for not-yours / another relato / not found / already a
		-- correction: there is no reply to a reply, and a correction is corrected
		-- only through the reply it corrects.
		IF corrected.id IS NULL OR corrected.account_id IS DISTINCT FROM account.id
		   OR corrected.author_profile_id IS DISTINCT FROM me.id
		   OR corrected.corrects_id IS NOT NULL THEN
			RAISE EXCEPTION 'Resposta a corrigir não encontrada.'
				USING ERRCODE = 'insufficient_privilege';
		END IF;
		IF EXISTS (SELECT 1 FROM public.day_account_replies r WHERE r.corrects_id = corrected.id) THEN
			RAISE EXCEPTION 'Esta resposta já foi corrigida.'
				USING ERRCODE = 'check_violation';
		END IF;
	END IF;

	INSERT INTO public.day_account_replies (family_id, account_id, author_profile_id, body, corrects_id)
	VALUES (me.family_id, account.id, me.id, body, p_corrects_id)
	RETURNING id INTO new_id;

	-- In-app only, to the relato's author: the push dispatcher's type filter
	-- does not name `day_account_reply`. The stored text is the PT-BR
	-- fallback, byte for byte the catalog's (the gate renders both).
	INSERT INTO public.notifications (recipient_profile_id, type, title, message, params)
	SELECT p.id, 'day_account_reply', 'Resposta ao relato',
	       me.full_name
	           || CASE WHEN p_corrects_id IS NULL THEN ' respondeu ao seu relato sobre '
	                   ELSE ' corrigiu a resposta ao seu relato sobre ' END
	           || to_char(account.account_date, 'DD/MM/YYYY') || '.',
	       jsonb_build_object(
	           'kind', CASE WHEN p_corrects_id IS NULL THEN 'new' ELSE 'correction' END,
	           'name', me.full_name,
	           'date', to_char(account.account_date, 'YYYY-MM-DD'))
	FROM public.profiles p
	WHERE p.id = account.author_profile_id
	  AND p.left_at IS NULL
	  AND p.user_id IS NOT NULL;

	RETURN new_id;
END;
$$;

ALTER FUNCTION public.add_day_account_reply(bigint, text, bigint) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.add_day_account_reply(bigint, text, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.add_day_account_reply(bigint, text, bigint) TO authenticated;
GRANT ALL    ON FUNCTION public.add_day_account_reply(bigint, text, bigint) TO service_role;

-- ── 4. F-69: the operator's report counts the replies — never their text ────
-- Body from 20260924170000_f35_chat.sql plus `replies` in the week rows and
-- `replies` / `reply_corrections` under `day_accounts`.

CREATE OR REPLACE FUNCTION public.admin_family_usage_report(p_family_id bigint)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	fam        public.families%ROWTYPE;
	today      date := (now() AT TIME ZONE 'America/Sao_Paulo')::date;
	first_week date;
	weeks      int := public.setting_int('usage_report.weeks', 12);
	active_win int := public.setting_int('usage_report.active_days', 30);
	premium    boolean;
	result     jsonb;
BEGIN
	IF NOT public.is_platform_operator() THEN
		RAISE EXCEPTION 'Acesso restrito à operação da plataforma.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	SELECT * INTO fam FROM public.families WHERE id = p_family_id;

	INSERT INTO public.operator_audit_logs (operator_user_id, action, family_id, new_value)
	VALUES (auth.uid(), 'family_usage_report', fam.id, p_family_id::text);

	IF fam.id IS NULL THEN
		RETURN NULL;
	END IF;

	premium    := public.is_premium(fam.id);
	first_week := date_trunc('week', today)::date - 7 * (weeks - 1);

	WITH
	days AS (
		SELECT
			d.schedule_date                                       AS day,
			COALESCE(d.actual_parent_id, d.scheduled_parent_id)   AS carer,
			d.scheduled_parent_id                                 AS planned,
			d.actual_parent_id                                    AS actual,
			d.handoff_time,
			NULLIF(btrim(d.notes), '') IS NOT NULL                AS has_note,
			(p.id IS NULL
			 OR COALESCE(p.actual_parent_id, p.scheduled_parent_id)
			    IS DISTINCT FROM COALESCE(d.actual_parent_id, d.scheduled_parent_id))
			                                                      AS transition
		FROM public.care_schedules d
		LEFT JOIN public.care_schedules p
		       ON p.family_id = d.family_id AND p.schedule_date = d.schedule_date - 1
		WHERE d.family_id = fam.id
	),
	edits AS (
		SELECT
			(l.created_at AT TIME ZONE 'America/Sao_Paulo')::date AS day,
			l.performed_by_id,
			COALESCE(l.context ->> 'batch_id',
			         l.performed_by_id::text || '@' || l.created_at::text) AS unit,
			COALESCE((l.context ->> 'admin_override')::boolean, false) AS override
		FROM public.activity_logs l
		WHERE l.family_id = fam.id
		  AND l.created_at >= (first_week::timestamp AT TIME ZONE 'America/Sao_Paulo')
	),
	weeks AS (
		SELECT w::date AS week_start
		FROM generate_series(first_week, date_trunc('week', today)::date, interval '7 days') w
	)
	SELECT jsonb_build_object(
		'report_version', 1,
		'generated_at',   now(),
		'today',          today,
		'windows',        jsonb_build_object('weeks', weeks, 'active_days', active_win),

		'family', jsonb_build_object(
			'id',              fam.id,
			'created_at',      fam.created_at,
			'plan',            fam.plan,
			'is_premium',      premium,
			'trial_ends_at',   fam.trial_ends_at,
			'comp_premium_at', fam.comp_premium_at,
			'seats_used',      public.seat_count(fam.id),
			'seats_cap',       CASE WHEN premium
			                        THEN public.setting_int('max_caregivers', 4)
			                        ELSE public.setting_int('free_caregivers', 2) END,
			-- F-50: the viewers, outside the caregiver seats — counts only.
			'viewers_used',    (SELECT COUNT(*) FROM public.profiles v
			                    WHERE v.family_id = fam.id AND v.membership_type = 'viewer'
			                      AND v.left_at IS NULL),
			'viewers_cap',     CASE WHEN premium
			                        THEN public.setting_int('max_viewers', 4)
			                        ELSE public.setting_int('free_viewers', 1) END,
			-- F-34: the expenses — counts only, never an amount or a text.
			'expenses', jsonb_build_object(
				'active',   (SELECT COUNT(*) FROM public.expenses x
				             WHERE x.family_id = fam.id AND x.deleted_at IS NULL),
				'deleted',  (SELECT COUNT(*) FROM public.expenses x
				             WHERE x.family_id = fam.id AND x.deleted_at IS NOT NULL),
				'edits',    (SELECT COUNT(*) FROM public.expense_history h
				             WHERE h.family_id = fam.id AND h.action = 'updated'),
				'settlements_pending',   (SELECT COUNT(*) FROM public.expense_settlements st
				                          WHERE st.family_id = fam.id AND st.status = 'pending'),
				'settlements_confirmed', (SELECT COUNT(*) FROM public.expense_settlements st
				                          WHERE st.family_id = fam.id AND st.status = 'confirmed')),
			-- F-64: the verifiable reports — counts only, never the id.
			'attestations', (
				SELECT jsonb_build_object(
					'issued',  COUNT(*),
					'active',  COUNT(*) FILTER (WHERE ra.revoked_at IS NULL AND ra.expires_at > now()
					                              AND ra.sha256 IS NOT NULL),
					'revoked', COUNT(*) FILTER (WHERE ra.revoked_at IS NOT NULL),
					'pending', COUNT(*) FILTER (WHERE ra.sha256 IS NULL AND ra.revoked_at IS NULL
					                              AND ra.expires_at > now()))
				FROM public.report_attestations ra WHERE ra.family_id = fam.id),
			-- F-35: the Conversa — counts only, never a text.
			'chat', (
				SELECT jsonb_build_object(
					'messages',     COUNT(*),
					'messages_30d', COUNT(*) FILTER (WHERE cm.created_at > now() - interval '30 days'),
					'authors',      COUNT(DISTINCT cm.author_profile_id))
				FROM public.chat_messages cm WHERE cm.family_id = fam.id),
			'chat_push_muted', (SELECT COUNT(*) FROM public.chat_prefs cp
			                    JOIN public.profiles pp ON pp.id = cp.profile_id
			                    WHERE pp.family_id = fam.id AND cp.push_muted),
			'viewer_invitations_open', (SELECT COUNT(*) FROM public.family_invitations vi
			                    WHERE vi.family_id = fam.id AND vi.member_type = 'viewer'
			                      AND vi.accepted_at IS NULL AND vi.revoked_at IS NULL
			                      AND vi.expires_at > now()),
			'subscription', (
				SELECT jsonb_build_object(
					'gateway',            s.gateway,
					'status',             s.status,
					'cycle',              s.cycle,
					'current_period_end', s.current_period_end,
					'overdue_since',      s.overdue_since,
					'canceled_at',        s.canceled_at
				)
				FROM public.subscriptions s WHERE s.family_id = fam.id
			),
			'invitations', (
				SELECT jsonb_build_object(
					'open',     COUNT(*) FILTER (WHERE i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > now()),
					'accepted', COUNT(*) FILTER (WHERE i.accepted_at IS NOT NULL),
					'expired',  COUNT(*) FILTER (WHERE i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at <= now()),
					'revoked',  COUNT(*) FILTER (WHERE i.accepted_at IS NULL AND i.revoked_at IS NOT NULL),
					'oldest_open_created_at',
					            MIN(i.created_at) FILTER (WHERE i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > now())
				)
				FROM public.family_invitations i WHERE i.family_id = fam.id
			)
		),

		'members', (
			SELECT COALESCE(jsonb_agg(jsonb_build_object(
				'profile_id',             p.id,
				'role',                   CASE WHEN r.family_id IS NULL THEN r.role ELSE 'custom' END,
				'is_admin',               p.is_admin,
				'membership',             p.membership_type,
				'state',                  CASE WHEN p.left_at IS NOT NULL THEN 'departed'
				                               WHEN p.user_id IS NULL     THEN 'pending'
				                               ELSE 'active' END,
				'created_at',             p.created_at,
				'joined_via_invite',      p.joined_via_invite,
				'left_at',                p.left_at,
				'has_password',           (SELECT COALESCE(u.encrypted_password, '') <> ''
				                           FROM auth.users u WHERE u.id = p.user_id),
				'has_google',             EXISTS (SELECT 1 FROM auth.identities i
				                                  WHERE i.user_id = p.user_id AND i.provider = 'google'),
				'language',               p.language_effective,
				'tour_seen_at',           p.onboarding_tour_seen_at,
				'consent_policy_version', p.consent_policy_version,
				'consent_accepted_at',    p.consent_accepted_at,
				'last_active_day',        la.last_day,
				'last_active_source',     la.last_source,
				'active_days_30', (
					SELECT COUNT(DISTINCT a.day) FROM public.member_activity_days a
					WHERE a.profile_id = p.id AND a.day > today - active_win
				),
				'channels_30', (
					SELECT COALESCE(jsonb_agg(DISTINCT a.channel), '[]'::jsonb)
					FROM public.member_activity_days a
					WHERE a.profile_id = p.id AND a.day > today - active_win
				),
				'devices', (
					SELECT COALESCE(jsonb_agg(jsonb_build_object(
						'platform',     ps.platform,
						'count',        ps.n,
						'last_seen_at', ps.last_seen
					) ORDER BY ps.platform), '[]'::jsonb)
					FROM (
						SELECT platform, COUNT(*) AS n, MAX(last_seen_at) AS last_seen
						FROM public.push_subscriptions
						WHERE profile_id = p.id
						GROUP BY platform
					) ps
				),
				'unread', (
					SELECT COALESCE(jsonb_agg(jsonb_build_object(
						'type',  un.type,
						'count', un.n
					) ORDER BY un.type), '[]'::jsonb)
					FROM (
						SELECT type, COUNT(*) AS n
						FROM public.notifications
						WHERE recipient_profile_id = p.id AND NOT COALESCE(is_read, false)
						GROUP BY type
					) un
				)
			) ORDER BY p.id), '[]'::jsonb)
			FROM public.profiles p
			LEFT JOIN public.roles r ON r.id = p.role_id
			LEFT JOIN LATERAL public.member_last_active(p.id) la ON true
			WHERE p.family_id = fam.id
		),

		'plan', (
			SELECT jsonb_build_object(
				'first_day',                   MIN(day),
				'last_day',                    MAX(day),
				'days_total',                  COUNT(*),
				'days_ahead',                  COUNT(*) FILTER (WHERE day >= today),
				'days_with_handoff_time',      COUNT(*) FILTER (WHERE handoff_time IS NOT NULL),
				'days_with_note',              COUNT(*) FILTER (WHERE has_note),
				'days_diverged',               COUNT(*) FILTER (WHERE actual IS NOT NULL AND actual IS DISTINCT FROM planned),
				'transitions_ahead',           COUNT(*) FILTER (WHERE day >= today AND transition),
				'transitions_ahead_with_time', COUNT(*) FILTER (WHERE day >= today AND transition AND handoff_time IS NOT NULL),
				'carers_ahead', (
					SELECT COALESCE(jsonb_agg(jsonb_build_object(
						'profile_id', c.carer,
						'days',       c.n
					) ORDER BY c.carer), '[]'::jsonb)
					FROM (
						SELECT carer, COUNT(*) AS n FROM days
						WHERE day >= today AND carer IS NOT NULL
						GROUP BY carer
					) c
				)
			)
			FROM days
		),

		'weeks', (
			SELECT COALESCE(jsonb_agg(jsonb_build_object(
				'week_start', wk.week_start,
				'edits', (
					SELECT COUNT(DISTINCT e.unit) FROM edits e
					WHERE e.day >= wk.week_start AND e.day < wk.week_start + 7
				),
				'edits_by_member', (
					SELECT COALESCE(jsonb_agg(jsonb_build_object(
						'profile_id', em.performed_by_id,
						'count',      em.n
					) ORDER BY em.performed_by_id), '[]'::jsonb)
					FROM (
						SELECT e.performed_by_id, COUNT(DISTINCT e.unit) AS n
						FROM edits e
						WHERE e.day >= wk.week_start AND e.day < wk.week_start + 7
						GROUP BY e.performed_by_id
					) em
				),
				'admin_overrides', (
					SELECT COUNT(DISTINCT e.unit) FROM edits e
					WHERE e.override AND e.day >= wk.week_start AND e.day < wk.week_start + 7
				),
				'swaps_opened', (
					SELECT COUNT(*) FROM public.swap_requests s
					WHERE s.family_id = fam.id
					  AND (s.created_at AT TIME ZONE 'America/Sao_Paulo')::date >= wk.week_start
					  AND (s.created_at AT TIME ZONE 'America/Sao_Paulo')::date <  wk.week_start + 7
				),
				'swaps_resolved', (
					SELECT COUNT(*) FROM public.swap_requests s
					WHERE s.family_id = fam.id
					  AND (s.resolved_at AT TIME ZONE 'America/Sao_Paulo')::date >= wk.week_start
					  AND (s.resolved_at AT TIME ZONE 'America/Sao_Paulo')::date <  wk.week_start + 7
				),
				'notices', (
					SELECT COUNT(*) FROM public.day_notices n
					WHERE n.family_id = fam.id
					  AND (n.created_at AT TIME ZONE 'America/Sao_Paulo')::date >= wk.week_start
					  AND (n.created_at AT TIME ZONE 'America/Sao_Paulo')::date <  wk.week_start + 7
				),
				'agenda_events', (
					SELECT COUNT(*) FROM public.child_events ce
					WHERE ce.family_id = fam.id AND ce.source_schedule_id IS NULL
					  AND ce.batch_id IS NULL
					  AND (ce.created_at AT TIME ZONE 'America/Sao_Paulo')::date >= wk.week_start
					  AND (ce.created_at AT TIME ZONE 'America/Sao_Paulo')::date <  wk.week_start + 7
				),
				'day_accounts', (
					SELECT COUNT(*) FROM public.day_accounts da
					WHERE da.family_id = fam.id
					  AND (da.created_at AT TIME ZONE 'America/Sao_Paulo')::date >= wk.week_start
					  AND (da.created_at AT TIME ZONE 'America/Sao_Paulo')::date <  wk.week_start + 7
				),
				'day_account_replies', (
					SELECT COUNT(*) FROM public.day_account_replies dr
					WHERE dr.family_id = fam.id
					  AND (dr.created_at AT TIME ZONE 'America/Sao_Paulo')::date >= wk.week_start
					  AND (dr.created_at AT TIME ZONE 'America/Sao_Paulo')::date <  wk.week_start + 7
				),
				'active_members', (
					SELECT COUNT(DISTINCT a.profile_id)
					FROM public.member_activity_days a
					JOIN public.profiles p ON p.id = a.profile_id
					WHERE p.family_id = fam.id
					  AND a.day >= wk.week_start AND a.day < wk.week_start + 7
				)
			) ORDER BY wk.week_start), '[]'::jsonb)
			FROM weeks wk
		),

		'swaps', jsonb_build_object(
			'by_status', (
				SELECT COALESCE(jsonb_agg(jsonb_build_object(
					'status',      bs.status,
					'resolved_by', bs.resolved_by,
					'count',       bs.n
				) ORDER BY bs.status, bs.resolved_by), '[]'::jsonb)
				FROM (
					SELECT status, resolved_by, COUNT(*) AS n
					FROM public.swap_requests
					WHERE family_id = fam.id
					GROUP BY status, resolved_by
				) bs
			),
			-- The COUNTERPART's answer: approved or rejected by a person. A
			-- cancellation is the requester's own act and an auto-approval
			-- (F-24, resolved_by 'system') is nobody's — both would skew it.
			'median_answer_hours', (
				SELECT round((percentile_cont(0.5) WITHIN GROUP (
					ORDER BY extract(epoch FROM s.resolved_at - s.created_at) / 3600.0))::numeric, 1)
				FROM public.swap_requests s
				WHERE s.family_id = fam.id
				  AND s.resolved_by = 'user'
				  AND s.status IN ('approved', 'rejected', 'revert_approved', 'revert_rejected')
				  AND s.resolved_at IS NOT NULL
			),
			'pending', (
				SELECT COUNT(*) FROM public.swap_requests s
				WHERE s.family_id = fam.id AND s.status IN ('pending', 'revert_pending')
			),
			'oldest_pending_created_at', (
				SELECT MIN(s.created_at) FROM public.swap_requests s
				WHERE s.family_id = fam.id AND s.status IN ('pending', 'revert_pending')
			)
		),

		'notices', jsonb_build_object(
			'total', (SELECT COUNT(*) FROM public.day_notices n WHERE n.family_id = fam.id),
			'by_outcome', (
				SELECT COALESCE(jsonb_agg(jsonb_build_object(
					'outcome', bo.outcome,
					'count',   bo.n
				) ORDER BY bo.outcome), '[]'::jsonb)
				FROM (
					SELECT COALESCE(o.outcome, 'none') AS outcome, COUNT(*) AS n
					FROM public.day_notices n
					LEFT JOIN public.day_notice_outcomes o ON o.notice_id = n.id
					WHERE n.family_id = fam.id
					GROUP BY COALESCE(o.outcome, 'none')
				) bo
			)
		),

		'day_accounts', jsonb_build_object(
			'total',       (SELECT COUNT(*) FROM public.day_accounts da WHERE da.family_id = fam.id),
			'corrections', (SELECT COUNT(*) FROM public.day_accounts da
			                WHERE da.family_id = fam.id AND da.corrects_id IS NOT NULL),
			-- F-75: the replies, counted like the relatos — never their text.
			'replies',           (SELECT COUNT(*) FROM public.day_account_replies dr
			                      WHERE dr.family_id = fam.id),
			'reply_corrections', (SELECT COUNT(*) FROM public.day_account_replies dr
			                      WHERE dr.family_id = fam.id AND dr.corrects_id IS NOT NULL)
		),

		-- F-55: the child entity and the agenda — counts only, never a name
		-- or an event's text.
		'agenda', jsonb_build_object(
			'children',       (SELECT COUNT(*) FROM public.children c WHERE c.family_id = fam.id),
			'events_active',  (SELECT COUNT(*) FROM public.child_events ce
			                   WHERE ce.family_id = fam.id AND ce.deleted_at IS NULL),
			'events_ahead',   (SELECT COUNT(*) FROM public.child_events ce
			                   WHERE ce.family_id = fam.id AND ce.deleted_at IS NULL
			                     AND ce.event_date >= today),
			'events_deleted', (SELECT COUNT(*) FROM public.child_events ce
			                   WHERE ce.family_id = fam.id AND ce.deleted_at IS NOT NULL),
			'notes_active',   (SELECT COUNT(*) FROM public.child_events ce
			                   WHERE ce.family_id = fam.id AND ce.deleted_at IS NULL
			                     AND ce.kind = 'note'),
			'converted',      (SELECT COUNT(*) FROM public.child_events ce
			                   WHERE ce.family_id = fam.id AND ce.source_schedule_id IS NOT NULL),
			'routines',       (SELECT COUNT(*) FROM public.child_routines cr
			                   WHERE cr.family_id = fam.id AND cr.stopped_at IS NULL),
			'events_from_routine', (SELECT COUNT(*) FROM public.child_events ce
			                   WHERE ce.family_id = fam.id AND ce.deleted_at IS NULL
			                     AND ce.batch_id IS NOT NULL),
			'with_reminder',  (SELECT COUNT(*) FROM public.child_events ce
			                   WHERE ce.family_id = fam.id AND ce.deleted_at IS NULL
			                     AND ce.remind_minutes IS NOT NULL),
			'reminders_sent', (SELECT COUNT(*) FROM public.child_events ce
			                   WHERE ce.family_id = fam.id AND ce.reminded_at IS NOT NULL),
			'by_kind', (
				SELECT COALESCE(jsonb_agg(jsonb_build_object(
					'kind',  bk.kind,
					'count', bk.n
				) ORDER BY bk.kind), '[]'::jsonb)
				FROM (
					SELECT kind, COUNT(*) AS n FROM public.child_events
					WHERE family_id = fam.id AND deleted_at IS NULL
					GROUP BY kind
				) bk
			)
		)
	) INTO result;

	RETURN result;
END;
$$;
