-- =============================================================================
-- F-67 — Relato do dia: what happened on a day that has passed
--
-- Field evidence (family 19, 19/09/2026 10:32–10:36 BRT): the mother sent two
-- F-52 avisos whose note described the day BEFORE — who picked the child up,
-- at what time, where they left them — and cancelled both, spending her cap of
-- two a day. The aviso is about today by construction, and the day's
-- Observação is a column of `care_schedules`, which `enforce_day_protection`
-- refuses to touch on a past day. The only door was the admin override, which
-- rewrites a PLAN field after the fact and stamps `admin_override` (F-61): it
-- reads "the admin changed the plan alone", not "someone told what happened".
--
-- **The plan is immutable; what happened is APPENDED** (owner, 21/09/2026).
-- A relato is a new row, never an edit of the schedule nor of the Observação,
-- and never itself edited: a correction is another relato whose `corrects_id`
-- points at the one it corrects, and both stay on the record.
--
-- **No dependency on `care_schedules`.** The key is (family, date): an
-- unplanned day can still get a relato, and nothing here fires the T-27/T-45
-- triggers or enters `enforce_day_protection`.
--
-- **Append-only by GRANT, not by trigger** — the `account_logs` / F-52 shape.
-- `authenticated` holds SELECT and nothing else; the one writer is the
-- SECURITY DEFINER function below. A trigger refusing DELETE would also refuse
-- the cascade a family purge depends on.
--
-- Decisions locked with the owner (21/09/2026): any ACTIVE member with an
-- account writes (a pending member has no account; a departed one is frozen,
-- S-11); the window is D-1 … D-`max_days_back`, in `America/Sao_Paulo`, and
-- TODAY is refused — today has the Observação and the aviso; 1 000 characters;
-- at most 10 relatos per author per day written; the other members are told
-- IN THE APP only (the type is not in `dispatch_push_notification`'s list, so
-- F-09's ten push types stay ten); writing is free.
-- =============================================================================

-- ── 1. Parameters (public: the client mirrors them to refuse upfront) ────────

INSERT INTO public.app_settings (key, value, value_type, category, description, is_public) VALUES
	('day_account.max_days_back', '30',   'int', 'product', 'F-67: quantos dias para trás um relato do dia pode ser registrado (D-1 … D-N; hoje nunca).', true),
	('day_account.max_chars',     '1000', 'int', 'product', 'F-67: tamanho máximo do texto de um relato do dia.', true),
	('day_account.daily_cap',     '10',   'int', 'product', 'F-67: relatos que um mesmo autor pode registrar num mesmo dia (teto contra abuso, dito antes de bloquear).', true)
ON CONFLICT (key) DO NOTHING;

-- ── 2. day_accounts ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.day_accounts (
	id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	family_id         bigint NOT NULL REFERENCES public.families (id) ON DELETE CASCADE,
	account_date      date   NOT NULL,
	author_profile_id bigint NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
	body              text   NOT NULL CHECK (char_length(body) BETWEEN 1 AND 4000),
	corrects_id       bigint REFERENCES public.day_accounts (id) ON DELETE CASCADE,
	created_at        timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL
);

-- The CHECK is a backstop, not the rule: the rule is `day_account.max_chars`,
-- read by the RPC, so the owner can move it without a migration.

CREATE INDEX IF NOT EXISTS day_accounts_family_date_idx
	ON public.day_accounts (family_id, account_date, created_at);

CREATE INDEX IF NOT EXISTS day_accounts_author_created_idx
	ON public.day_accounts (author_profile_id, created_at);

-- One correction per relato: a chain is corrected at its newest link, so the
-- record never shows two competing "corrected" versions of the same text.
CREATE UNIQUE INDEX IF NOT EXISTS day_accounts_one_correction_idx
	ON public.day_accounts (corrects_id) WHERE corrects_id IS NOT NULL;

COMMENT ON TABLE public.day_accounts IS
	'F-67: a dated account of what happened on a PAST day, by an active member. Append-only — authenticated holds SELECT only; the one writer is add_day_account. A correction is a new row pointing at the corrected one (corrects_id).';
COMMENT ON COLUMN public.day_accounts.account_date IS
	'F-67: the day the relato is ABOUT. created_at is when it was WRITTEN; the record prints both.';

ALTER TABLE public.day_accounts OWNER TO postgres;
ALTER TABLE public.day_accounts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.day_accounts FROM PUBLIC;
REVOKE ALL ON TABLE public.day_accounts FROM anon;
REVOKE ALL ON TABLE public.day_accounts FROM authenticated;
GRANT SELECT ON TABLE public.day_accounts TO authenticated;
GRANT ALL    ON TABLE public.day_accounts TO service_role;

DROP POLICY IF EXISTS day_accounts_family_read ON public.day_accounts;
CREATE POLICY day_accounts_family_read ON public.day_accounts
	FOR SELECT TO authenticated
	USING (family_id = public.get_my_family_id());

-- ── 3. add_day_account ───────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.add_day_account(
	p_date        date,
	p_body        text,
	p_corrects_id bigint DEFAULT NULL)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	me         public.profiles%ROWTYPE;
	tz         constant text := 'America/Sao_Paulo';
	today      date := (now() AT TIME ZONE tz)::date;
	days_back  int  := public.setting_int('day_account.max_days_back', 30);
	max_chars  int  := public.setting_int('day_account.max_chars', 1000);
	daily_cap  int  := public.setting_int('day_account.daily_cap', 10);
	body       text := nullif(btrim(p_body), '');
	corrected  public.day_accounts%ROWTYPE;
	written    int;
	new_id     bigint;
	d          text;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();

	-- A departed member (S-11) is frozen; a pending one (F-56) has no account
	-- to act with, so `auth.uid()` never finds it.
	IF me.id IS NULL OR me.left_at IS NOT NULL THEN
		RAISE EXCEPTION 'Sua conta não pode registrar relatos.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	IF p_date IS NULL OR p_date >= today THEN
		RAISE EXCEPTION 'Um relato é sobre um dia que já passou.'
			USING ERRCODE = 'check_violation';
	END IF;

	IF p_date < today - days_back THEN
		RAISE EXCEPTION 'Relatos podem ser registrados até % dias depois do dia.', days_back
			USING ERRCODE = 'check_violation';
	END IF;

	IF body IS NULL THEN
		RAISE EXCEPTION 'O relato não pode ficar vazio.'
			USING ERRCODE = 'check_violation';
	END IF;

	IF char_length(body) > max_chars THEN
		RAISE EXCEPTION 'O relato é limitado a % caracteres.', max_chars
			USING ERRCODE = 'check_violation';
	END IF;

	IF p_corrects_id IS NOT NULL THEN
		SELECT * INTO corrected FROM public.day_accounts WHERE id = p_corrects_id;

		-- One message for "not yours", "another day" and "does not exist": a
		-- caller learning which of the three it was learns about another
		-- family's rows. And only the AUTHOR corrects a relato — someone else
		-- who remembers it differently writes their own, and the record keeps
		-- both voices instead of letting one mark the other "corrigido".
		IF corrected.id IS NULL
		   OR corrected.family_id IS DISTINCT FROM me.family_id
		   OR corrected.account_date IS DISTINCT FROM p_date
		   OR corrected.author_profile_id IS DISTINCT FROM me.id THEN
			RAISE EXCEPTION 'Relato a corrigir não encontrado.'
				USING ERRCODE = 'insufficient_privilege';
		END IF;

		-- The partial UNIQUE below would refuse it anyway; this says WHY.
		IF EXISTS (SELECT 1 FROM public.day_accounts a WHERE a.corrects_id = corrected.id) THEN
			RAISE EXCEPTION 'Este relato já foi corrigido — corrija a versão mais recente.'
				USING ERRCODE = 'check_violation';
		END IF;
	END IF;

	-- Counted by the day WRITTEN, in São Paulo: an abuse ceiling, not a rule
	-- about the day told.
	SELECT count(*)::int INTO written
	FROM public.day_accounts
	WHERE author_profile_id = me.id
	  AND (created_at AT TIME ZONE tz)::date = today;

	IF written >= daily_cap THEN
		RAISE EXCEPTION 'Você já registrou % relatos hoje. O limite volta amanhã.', daily_cap
			USING ERRCODE = 'check_violation';
	END IF;

	INSERT INTO public.day_accounts (family_id, account_date, author_profile_id, body, corrects_id)
	VALUES (me.family_id, p_date, me.id, body, p_corrects_id)
	RETURNING id INTO new_id;

	-- In-app only: 'day_account' is not in dispatch_push_notification's list.
	-- The stored PT-BR is the FALLBACK (U-13); every reader rebuilds the
	-- sentence from `params`, and the gate asserts the two are byte-identical.
	d := to_char(p_date, 'DD/MM/YYYY');
	INSERT INTO public.notifications (recipient_profile_id, type, title, message, params)
	SELECT p.id, 'day_account', 'Relato do dia',
	       me.full_name
	           || CASE WHEN p_corrects_id IS NULL THEN ' registrou' ELSE ' corrigiu' END
	           || ' um relato sobre ' || d || '.',
	       jsonb_build_object(
	           'kind', CASE WHEN p_corrects_id IS NULL THEN 'new' ELSE 'correction' END,
	           'name', me.full_name,
	           'date', to_char(p_date, 'YYYY-MM-DD'))
	FROM public.profiles p
	WHERE p.family_id = me.family_id
	  AND p.id <> me.id
	  AND p.left_at IS NULL
	  AND p.user_id IS NOT NULL;

	RETURN new_id;
END;
$$;

ALTER FUNCTION public.add_day_account(date, text, bigint) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.add_day_account(date, text, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.add_day_account(date, text, bigint) TO authenticated;
GRANT ALL    ON FUNCTION public.add_day_account(date, text, bigint) TO service_role;
